### ISSUE TITLE
Update Readme with link to driver.

### ISSUE THREAD

**Issue by AlphaMoonbaseBerlin** [thepelkus-too/SlamtecLidarTDCPPCHOP#2]
On windows, if there is not internet or just a metered connection, Windows will not autoDownload the driver for the bridge.
Either force it to download via windowsUpdate or download the drivers directly.
https://www.silabs.com/developers/usb-to-uart-bridge-vcp-drivers?tab=downloads

Might just be a good thing to note in the docs :)

**Comment by thepelkus-too** [comment]
Thanks for the heads up; I'll throw it in the docs! 🙏

**Comment by thepelkus-too** [comment]
Added to README in https://github.com/thepelkus-too/SlamtecLidarTDCPPCHOP/commit/442e626483ab015dd1365fc353f8029fd6062eea
